---
site_name: "CScanner: A Cloud Security Scanner"
repo_url: https://github.com/janoszen/cscanner/
theme: readthedocs
nav:
  - "Home": "index.md"
  - "Cloud providers":
      - "Amazon Web Services": "clouds/aws.md"
      - "Exoscale": "clouds/exoscale.md"
  - "Rules":
      - "Firewall": "rules/firewall.md"
      - "S3": "rules/s3.md"
