site_name: "CScanner: A Cloud Security Scanner"
site_url: "https://cscanner.io"
repo_url: "https://github.com/janoszen/cscanner/"
markdown_extensions:
  - admonition
theme:
  name: readthedocs
  custom_dir: ./docs/.theme/
  include_sidebar: false
  static_templates:
    - .circleci/config.yml
nav:
- 'Home': 'index.md'
- 'Cloud providers':
  - 'Amazon Web Services': 'clouds/aws.md'
  - 'Exoscale': 'clouds/exoscale.md'
- 'Rules':
  - 'Firewall': 'rules/firewall.md'
  - 'S3': 'rules/s3.md'
- 'Development':
  - 'Contributing to CScanner': 'dev/dev.md'
  - 'Writing a Provider': 'dev/provider.md'
  - 'Writing a Rule': 'dev/rule.md'
site_favicon: img/favicon.png
extra_css:
  - css/custom.css