---
version: 2
jobs:
workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build-branch:
        filters:
          branches:
            ignore: gh-pages
          tags:
            ignore: /.*/
